use cafeteria_DB
go

create or alter view V_ADMIN_INFOR
as
	select ID_ADMIN, EMAIL
	from ADMIN
	where EMAIL = CURRENT_USER
go

create or alter view V_ADMIN_UPDATE_DELETE_INFOR
as
	select EMAIL, PASSWORDHASH
	from ADMIN
	where EMAIL = CURRENT_USER
go

create or alter view V_ADMIN_TABLE
as
	select ID_TABLE, ID_SHAPE, TABLE_STATUS, X_COORDINATE, Y_COORDINATE
	from CAFETERIA_TABLE
go

create or alter view V_ADMIN_CANVA_ADMIN
as
	select CA.LOGIN_STATUS
	from CANVA_ADMIN CA, ADMIN AD
    where AD.EMAIL = CURRENT_USER
        AND AD.ID_ADMIN = CA.ID_ADMIN
go

create or alter view V_ADMIN_FOOD_TABLE
as
	select *
	from FOOD_TABLE
go

GRANT SELECT, INSERT, UPDATE, DELETE ON SHAPE_TYPE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON FOOD_TYPE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_TABLE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON CANVA TO ADMIN

GRANT SELECT ON V_ADMIN_INFOR TO ADMIN

GRANT SELECT, UPDATE, DELETE ON V_ADMIN_UPDATE_DELETE_INFOR TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_CANVA_ADMIN TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_FOOD_TABLE TO ADMIN
GO

