-- Create the database  
CREATE DATABASE cafeteriaDB;
--DROP DATABASE cafeteriaDB;

-- Use the created database  
USE cafeteriaDB;
--USE MASTER;

-- Create the CANVA table  
CREATE TABLE CANVA (  
    ID_CANVA VARCHAR(5) PRIMARY KEY,  
    WIDTH FLOAT,  
    HEIGHT FLOAT
);

-- Create the ADMIN table  
CREATE TABLE ADMIN (  
    ID_ADMIN VARCHAR(5) PRIMARY KEY,  
    EMAIL VARCHAR(255),  
    PASSWORDHASH VARBINARY(64),
    SALT VARBINARY(16)
);
-- ALTER TABLE ADMIN
-- ADD Salt VARBINARY(16);

-- -- Step 1: Add a new PasswordHash column with the VARBINARY type
-- ALTER TABLE ADMIN
-- ADD PasswordHash VARBINARY(64);

-- -- Step 2: Copy data from the old PASSWORD column if needed
-- -- This step is only if you still need the old data in some way.
-- -- Ideally, rehash the passwords before inserting into PasswordHash.
-- UPDATE ADMIN
-- SET PasswordHash = CONVERT(VARBINARY(64), PASSWORD);

-- -- Step 3: Drop the old PASSWORD column
-- ALTER TABLE ADMIN
-- DROP COLUMN PASSWORD;

-- Create the CANVA_ADMIN table  
CREATE TABLE CANVA_ADMIN (  
    ID_CANVA VARCHAR(5),  
    ID_ADMIN VARCHAR(5),
    LOGIN_STATUS VARCHAR(50),  
    PRIMARY KEY (ID_CANVA, ID_ADMIN),  
    FOREIGN KEY (ID_CANVA) REFERENCES CANVA(ID_CANVA),  
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(ID_ADMIN)
);

-- Create the SHAPE_TYPE table  
CREATE TABLE SHAPE_TYPE (  
    ID_SHAPE VARCHAR(5) PRIMARY KEY,
    WIDTH FLOAT,  
    HEIGHT FLOAT,
    RADIUS FLOAT,
    MIDPOINT_X_COORDINATE FLOAT,
    MIDPOINT_Y_COORDINATE FLOAT,
    SHAPE_TYPENAME VARCHAR(50),  
);

-- Create the CAFETERIA_TABLE table  
CREATE TABLE CAFETERIA_TABLE (  
    ID_TABLE VARCHAR(5) PRIMARY KEY,  
    ID_SHAPE VARCHAR(5),  
    ID_CANVA VARCHAR(5),
    ID_ADMIN VARCHAR(5),
    TABLE_STATUS VARCHAR(50),
    FOREIGN KEY (ID_SHAPE) REFERENCES SHAPE_TYPE(ID_SHAPE),
    FOREIGN KEY (ID_CANVA, ID_ADMIN) REFERENCES CANVA_ADMIN(ID_CANVA, ID_ADMIN)
);  

-- Create the FOOD_TYPE table  
CREATE TABLE FOOD_TYPE (  
    ID_FOOD VARCHAR(5) PRIMARY KEY,
    FOOD_NAME VARCHAR(255),
    AMOUNT_LEFT INT,  
    PRICE DECIMAL(10, 2),  
    FOOD_TYPE_STATUS VARCHAR(50)
);  

-- Create the FOOD_TABLE table  
CREATE TABLE FOOD_TABLE (  
    ID_FOOD VARCHAR(5),
    ID_TABLE VARCHAR(5),  
    AMOUNT_IN_TABLE INT,
    PRIMARY KEY (ID_FOOD),  
    FOREIGN KEY (ID_FOOD) REFERENCES FOOD_TYPE(ID_FOOD),
    FOREIGN KEY (ID_TABLE) REFERENCES CAFETERIA_TABLE(ID_TABLE)
);

ALTER TABLE FOOD_TABLE
DROP CONSTRAINT PK__FOOD_TAB__61DE7B3880806801;

ALTER TABLE FOOD_TABLE
ADD CONSTRAINT FOOD_TABLE_PK PRIMARY KEY (ID_TABLE, ID_FOOD);

SELECT 
    tc.CONSTRAINT_NAME, 
    tc.TABLE_NAME, 
    kcu.COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu 
    ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
WHERE tc.TABLE_NAME = 'ADMIN' AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY';

ALTER TABLE FOOD_TABLE
ALTER COLUMN ID_TABLE varchar(5) NOT NULL;
